apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: podtato-chaos-
  namespace: litmus
spec:
  arguments:
    parameters:
      - name: adminModeNamespace
        value: litmus
  entrypoint: podtato-chaos
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
    - name: podtato-chaos
      steps:
        - - name: install-chaos-experiments
            template: install-chaos-experiments
        - - name: pod-delete
            template: pod-delete
        - - name: revert-chaos
            template: revert-chaos
    - name: install-chaos-experiments
      container:
        args:
          - kubectl apply -f
            https://github.com/litmuschaos/chaos-charts/raw/master/charts/generic/pod-delete/experiment.yaml
            -n {{workflow.parameters.adminModeNamespace}} | sleep 30
        command:
          - sh
          - -c
        image: lachlanevenson/k8s-kubectl
    - name: pod-delete
      inputs:
        artifacts:
          - name: pod-delete
            path: /tmp/chaosengine-pod-delete.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                kind: ChaosEngine
                metadata:
                  name: pod-delete
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                spec:
                  appinfo:
                    appns: monitoring
                    applabel: app=helloservice
                    appkind: deployment
                  annotationCheck: "false"
                  engineState: active
                  chaosServiceAccount: litmus-admin
                  monitoring: true
                  jobCleanUpPolicy: delete
                  experiments:
                    - name: pod-delete
                      spec:
                        probe:
                        - name: helloservice-probe-duration-seconds
                          type: "promProbe"
                          promProbe/inputs:
                            endpoint: "http://34.66.52.205:31090"
                            query: "avg_over_time(probe_duration_seconds{instance='helloservice.monitoring.svc.cluster.local:80',job='blackbox'}[10s])*1000"
                            comparator:
                              criteria: "<="
                              value: "30" # in ms
                          mode: "Continuous" 
                          runProperties:
                            probeTimeout: 10
                            interval: 5
                            retry: 1
                            probePollingInterval: 2
                        - name: helloservice-liveness-check
                          type: "httpProbe"
                          mode: "Continuous"
                          httpProbe/inputs:
                            url: "http://35.238.211.100:80"
                            expectedResponseCode: "200"
                          runProperties:
                            probeTimeout: 10
                            interval: 5
                            retry: 1
                            probePollingInterval: 2
                        components:
                          env:
                            - name: TOTAL_CHAOS_DURATION
                              value: "30"
                            - name: CHAOS_INTERVAL
                              value: "10"
                            - name: FORCE
                              value: "false"
      container:
        args:
          - -file=/tmp/chaosengine-pod-delete.yaml
          - -saveName=/tmp/engine-name
        image: litmuschaos/litmus-checker:latest
    - name: revert-chaos
      container:
        args:
          - kubectl delete chaosengines --all -n
            {{workflow.parameters.adminModeNamespace}}
        command:
          - sh
          - -c
        image: lachlanevenson/k8s-kubectl


