{
 "title": "Kafka: Cluster Summary",
 "description": "KUDO Kafka Cluster Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "kafka_controller_ControllerStats_LeaderElectionRateAndTimeMs"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "kafka_controller_ControllerStats_LeaderElectionRateAndTimeMs"
    }
   },
   {
    "name": "broker",
    "query": {
     "query": "kafka_controller_ControllerStats_LeaderElectionRateAndTimeMs"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Broker Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_brokers{endpoint=\"metrics\",instance=\"10.4.5.64:9308\",job=\"kafka-exporter\",namespace=\"kafka\",pod=\"kafka-exporter-7f849cd58-wgz2r\",service=\"kafka-exporter\"}"
    }
   ]
  },
  {
   "title": "Zookeeper Sync Connects / sec",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kafka_server_SessionExpireListener_ZooKeeperSyncConnects_total{service=\"$service\"})"
    }
   ]
  },
  {
   "title": "Total Leader Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kafka_server_ReplicaManager_LeaderCount{namespace=\"$namespace\",service=\"$service\"})"
    }
   ]
  },
  {
   "title": "Total Topic Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count by (topic) (kafka_server_BrokerTopicMetrics_MessagesIn_total{namespace=\"$namespace\",service=\"$service\"}))"
    }
   ]
  },
  {
   "title": "Total Partition Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kafka_server_ReplicaManager_PartitionCount{namespace=\"$namespace\",service=\"$service\"})"
    }
   ]
  },
  {
   "title": "ActiveController for ($service)",
   "type": "graph",
   "description": "The first node to boot in a Kafka cluster automatically becomes the controller, and there can be only one. The controller in a Kafka cluster is responsible for maintaining the list of partition leaders, and coordinating leadership transitions (in the event a partition leader becomes unavailable). If it becomes necessary to replace the controller, a new controller is randomly chosen by ZooKeeper from the pool of brokers. In general, it is not possible for this value to be greater than one, but you should definitely alert on a value of zero that lasts for more than a short period (< 1s) of time.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_ActiveControllerCount{namespace=\"$namespace\",service=\"$service\"})by(pod, service)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk Usage: $broker",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (node_filesystem_size_bytes{mountpoint=\"/var/lib/kafka\",namespace=\"$namespace\",service=\"$service\",pod=\"$broker\"} - node_filesystem_avail_bytes{mountpoint=\"/var/lib/kafka\",namespace=\"$namespace\",service=\"$service\",pod=\"$broker\"}) / node_filesystem_size_bytes{mountpoint=\"/var/lib/kafka\",namespace=\"$namespace\",service=\"$service\",pod=\"$broker\"}",
     "legendFormat": "USED: {{$broker}}"
    }
   ]
  },
  {
   "title": "Request Handler Avg Load %",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(kafka_network_SocketServer_NetworkProcessorAvgIdlePercent{namespace=\"$namespace\",service=\"$service\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions for $service",
   "type": "singlestat",
   "description": "In a healthy cluster, the number of in sync replicas (ISRs) should be exactly equal to the total number of replicas. If partition replicas fall too far behind their leaders, the follower partition is removed from the ISR pool, and you should see a corresponding increase in IsrShrinksPerSec. Since Kafka’s high-availability guarantees cannot be met without replication, investigation is certainly warranted should this metric value exceed zero for extended time periods.\n\nIf this metric has a value greater than 1 it means that data is not being replicated to enough number of brokers thereby increasing the probability of data loss.",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_ReplicaManager_UnderReplicatedPartitions{service=\"$service\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Active Controller Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_ActiveControllerCount{namespace=\"$namespace\",service=\"$service\"})"
    }
   ]
  },
  {
   "title": "Total Messages In",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_MessagesIn_total{namespace=\"$namespace\",service=\"$service\", topic=\"\"})"
    }
   ]
  },
  {
   "title": "Total Messages In Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 9 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_BytesIn_total{namespace=\"$namespace\",service=\"$service\", topic=\"\"})"
    }
   ]
  },
  {
   "title": "Disk Used / Broker",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 9 },
   "targets": [
    {
     "expr": "100 * (node_filesystem_size_bytes{mountpoint=\"/var/lib/kafka\",namespace=\"$namespace\",service=\"$service\"} - node_filesystem_avail_bytes{mountpoint=\"/var/lib/kafka\",namespace=\"$namespace\",service=\"$service\"}) / node_filesystem_size_bytes{mountpoint=\"/var/lib/kafka\",namespace=\"$namespace\",service=\"$service\"}",
     "legendFormat": "{{pod}}: {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Memory Used / Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{namespace=\"$namespace\",service=\"$service\"}",
     "legendFormat": "{{pod}} {{area}}"
    }
   ]
  },
  {
   "title": "Messages / Topic",
   "type": "graph",
   "description": "Generally, disk throughput tends to be the main bottleneck in Kafka performance. However, that’s not to say that the network is never a bottleneck. Depending on your use case, hardware, and configuration, the network can quickly become the slowest segment of a message’s trip, especially if you are sending messages across data centers. Tracking network throughput on your brokers gives you more information as to where potential bottlenecks may lie, and can inform decisions like whether or not you should enable end-to-end compression of your messages.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(topic) (kafka_server_BrokerTopicMetrics_MessagesIn_total{namespace=\"$namespace\",service=\"$service\", topic=~\".+\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "messages in / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_BrokerTopicMetrics_MessagesIn_total{service=\"$service\", namespace=\"$namespace\", topic=\"\"}[1m]))",
     "legendFormat": "messages/second"
    }
   ]
  },
  {
   "title": "bytes in / sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_BrokerTopicMetrics_BytesIn_total{service=\"$service\", namespace=\"$namespace\", topic=\"\"}[1m]))",
     "legendFormat": "bytes in /second"
    }
   ]
  },
  {
   "title": "All Bytes In",
   "type": "graph",
   "description": "Generally, disk throughput tends to be the main bottleneck in Kafka performance. However, that’s not to say that the network is never a bottleneck. Depending on your use case, hardware, and configuration, the network can quickly become the slowest segment of a message’s trip, especially if you are sending messages across data centers. Tracking network throughput on your brokers gives you more information as to where potential bottlenecks may lie, and can inform decisions like whether or not you should enable end-to-end compression of your messages.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_BytesIn_total{namespace=\"$namespace\",service=\"$service\", topic=\"\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "All Bytes Out",
   "type": "graph",
   "description": "Generally, disk throughput tends to be the main bottleneck in Kafka performance. However, that’s not to say that the network is never a bottleneck. Depending on your use case, hardware, and configuration, the network can quickly become the slowest segment of a message’s trip, especially if you are sending messages across data centers. Tracking network throughput on your brokers gives you more information as to where potential bottlenecks may lie, and can inform decisions like whether or not you should enable end-to-end compression of your messages.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_BytesOut_total{namespace=\"$namespace\",service=\"$service\", topic=\"\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Broker Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Partition Count (Broker) for ($service) broker ($broker)",
     "type": "graph",
     "description": "The first node to boot in a Kafka cluster automatically becomes the controller, and there can be only one. The controller in a Kafka cluster is responsible for maintaining the list of partition leaders, and coordinating leadership transitions (in the event a partition leader becomes unavailable). If it becomes necessary to replace the controller, a new controller is randomly chosen by ZooKeeper from the pool of brokers. In general, it is not possible for this value to be greater than one, but you should definitely alert on a value of zero that lasts for more than a short period (< 1s) of time.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(kafka_controller_KafkaController_GlobalPartitionCount{namespace=\"$namespace\",service=\"$service\",pod=~\"$broker\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ISR Shrink Rate (Broker) for ($service) broker ($broker)",
     "type": "graph",
     "description": "The number of in-sync replicas (ISRs) for a particular partition should remain fairly static, the only exceptions are when you are expanding your broker cluster or removing partitions. In order to maintain high availability, a healthy Kafka cluster requires a minimum number of ISRs for failover. A replica could be removed from the ISR pool for a couple of reasons: it is too far behind the leader’s offset (user-configurable by setting the replica.lag.max.messages configuration parameter), or it has not contacted the leader for some time (configurable with the replica.socket.timeout.ms parameter). No matter the reason, an increase in IsrShrinksPerSec without a corresponding increase in IsrExpandsPerSec shortly thereafter is cause for concern and requires user intervention.The Kafka documentation provides a wealth of information on the user-configurable parameters for brokers.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(kafka_server_ReplicaManager_IsrShrinks_total{namespace=\"$namespace\",service=\"$service\",pod=~\"$broker\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Offline Partitions for ($service) broker ($broker)",
     "type": "graph",
     "description": "This value should be 0",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_controller_KafkaController_OfflinePartitionsCount{namespace=\"$namespace\",service=\"$service\",pod=~\"$broker\"})by(pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Producer Purgatory Requests Waiting for ($service) broker ($broker)",
     "type": "graph",
     "description": "Number of requests waiting in the producer purgatory. This should be non-zero when acks=all is used on the producer.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_server_DelayedOperationPurgatory_NumDelayedOperations{namespace=\"$namespace\",service=\"$service\",pod=~\"$broker\"})by(pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ISR Expansion Rate (Broker) for ($service) broker ($broker)",
     "type": "graph",
     "description": "The number of in-sync replicas (ISRs) for a particular partition should remain fairly static, the only exceptions are when you are expanding your broker cluster or removing partitions. In order to maintain high availability, a healthy Kafka cluster requires a minimum number of ISRs for failover. A replica could be removed from the ISR pool for a couple of reasons: it is too far behind the leader’s offset (user-configurable by setting the replica.lag.max.messages configuration parameter), or it has not contacted the leader for some time (configurable with the replica.socket.timeout.ms parameter). No matter the reason, an increase in IsrShrinksPerSec without a corresponding increase in IsrExpandsPerSec shortly thereafter is cause for concern and requires user intervention.The Kafka documentation provides a wealth of information on the user-configurable parameters for brokers.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_server_ReplicaManager_IsrExpands_total{namespace=\"$namespace\",service=\"$service\",pod=~\"$broker\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Delayed Fetch Operation Purgatory Size for ($service) broker ($broker)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_server_DelayedOperationPurgatory_PurgatorySize{namespace=\"$namespace\",service=\"$service\",pod=~\"$broker\"})by(pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Partition Count Across Brokers for ($service) broker ($broker)",
     "type": "graph",
     "description": "Number of partitions on this broker. This should be mostly even across all brokers.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(kafka_server_ReplicaManager_PartitionCount{namespace=\"$namespace\",service=\"$service\",pod=~\"$broker\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Derivative messages/sec for ($broker) / topic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_server_BrokerTopicMetrics_MessagesIn_total{namespace=\"$namespace\", service=\"$service\", pod=~\"$broker\", topic=~\".+\"}[2m])",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "All Bytes In per (Broker) for ($service) broker ($broker)",
     "type": "graph",
     "description": "Generally, disk throughput tends to be the main bottleneck in Kafka performance. However, that’s not to say that the network is never a bottleneck. Depending on your use case, hardware, and configuration, the network can quickly become the slowest segment of a message’s trip, especially if you are sending messages across data centers. Tracking network throughput on your brokers gives you more information as to where potential bottlenecks may lie, and can inform decisions like whether or not you should enable end-to-end compression of your messages.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "(kafka_server_BrokerTopicMetrics_BytesIn_total{namespace=\"$namespace\",service=\"$service\",pod=~\"$broker\", topic=~\".+\"})",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "All Bytes Out per (Broker) for ($service) broker ($broker)",
     "type": "graph",
     "description": "Generally, disk throughput tends to be the main bottleneck in Kafka performance. However, that’s not to say that the network is never a bottleneck. Depending on your use case, hardware, and configuration, the network can quickly become the slowest segment of a message’s trip, especially if you are sending messages across data centers. Tracking network throughput on your brokers gives you more information as to where potential bottlenecks may lie, and can inform decisions like whether or not you should enable end-to-end compression of your messages.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "(kafka_server_BrokerTopicMetrics_BytesOut_total{namespace=\"$namespace\",service=\"$service\",pod=~\"$broker\", topic=~\".+\"})",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "bytes in / sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kafka_server_BrokerTopicMetrics_BytesIn_total{namespace=\"$namespace\",service=\"$service\",pod=~\"$broker\"}[1m]))",
       "legendFormat": "{{ $broker }} - bytes in /second "
      }
     ]
    },
    {
     "title": "Under Replicated Partitions",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "sum by(topic) (kafka_cluster_Partition_UnderReplicated{namespace=\"$namespace\",namespace=\"$namespace\",service=\"$service\"})"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "graph",
     "description": "Generally, disk throughput tends to be the main bottleneck in Kafka performance. However, that’s not to say that the network is never a bottleneck. Depending on your use case, hardware, and configuration, the network can quickly become the slowest segment of a message’s trip, especially if you are sending messages across data centers. Tracking network throughput on your brokers gives you more information as to where potential bottlenecks may lie, and can inform decisions like whether or not you should enable end-to-end compression of your messages.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{mountpoint=\"/var/lib/kafka\",namespace=\"$namespace\",service=\"$service\",pod=\"$broker\"}",
       "legendFormat": "TOTAL: {{pod}}"
      },
      {
       "expr": "node_filesystem_size_bytes{mountpoint=\"/var/lib/kafka\",namespace=\"$namespace\",service=\"$service\",pod=\"$broker\"} - node_filesystem_avail_bytes{mountpoint=\"/var/lib/kafka\",namespace=\"$namespace\",service=\"$service\",pod=\"$broker\"}",
       "legendFormat": "USED: {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}